---
abstract: 'Redis-driven storage backend for Throttle-Lite'
author:
  - 'Anton Gerasimov <chim@cpan.org>'
build_requires:
  Test::More: 0.98
  Test::Pod: 1.22
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300030, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-Throttle-Lite-Backend-Redis
no_index:
  directory:
    - t
    - xt
    - eg
    - examples
    - corpus
  namespace:
    - t::lib
  package:
    - DB
provides:
  Plack::Middleware::Throttle::Lite::Backend::Redis:
    file: lib/Plack/Middleware/Throttle/Lite/Backend/Redis.pm
    version: 0.02
requires:
  Carp: 0
  Plack::Middleware::Throttle::Lite: 0.01
  Redis: 1.955
  feature: 0
  parent: 0
  perl: 5.010001
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/Wu-Wu/Plack-Middleware-Throttle-Lite-Backend-Redis/issues
  homepage: https://metacpan.org/release/Plack-Middleware-Throttle-Lite-Backend-Redis
  repository: git://github.com/Wu-Wu/Plack-Middleware-Throttle-Lite-Backend-Redis.git
version: 0.02
x_authority: cpan:CHIM
